tarefa_analise_texto:
  description: >
    Sua tarefa é analisar o <texto_base> e extrair as informações cruciais que servirão como base para
    a criação de um roteiro narrativo detalhado. Você deve identificar e organizar os seguintes elementos:

    - Conflito Inicial: O ponto de partida que desencadeia a ação ou o drama no texto. Identifique o evento, 
      situação ou problema que gera o conflito central.
    - Desenvolvimento: O progresso da história a partir do conflito inicial, incluindo os desafios e obstáculos 
      enfrentados pelos personagens ou ideias principais.
    - Clímax: O ponto de maior tensão ou virada na narrativa, onde o conflito atinge seu auge e as decisões 
      cruciais são tomadas.
    - Resolução: A solução ou desfecho do conflito, mostrando como os personagens ou ideias lidam com o clímax e 
      quais são as consequências.
    - Conclusão: O fechamento da história, onde todos os pontos principais são amarrados e a narrativa é concluída 
      de maneira satisfatória.

    Além de identificar os elementos acima, você deve associar cada um deles às emoções relevantes (ex.: raiva, 
    defesa, esperança) e tópicos de conversa principais que emergem ao longo da narrativa, garantindo que 
    esses pontos sirvam de base sólida para o roteirista.
    
    <texto_base>
    {texto_base}
    </texto_base>
  expected_output: >
    Você deverá entregar uma lista organizada dos elementos narrativos extraídos do <texto_base>, contendo o 
    Conflito Inicial, Desenvolvimento, Clímax, Resolução e Conclusão, junto com as emoções e tópicos de conversa 
    relevantes para cada um desses elementos. A saída deve ser clara e coesa, facilitando o uso dessas informações 
    na criação do roteiro. O resultado deve fornecer uma base sólida para o Agente Roteirista seguir na construção 
    do roteiro.

tarefa_criacao_roteiro:
  description: >
    Sua tarefa é criar um roteiro detalhado baseado nas informações fornecidas pelo Agente Analista de Texto, que 
    incluem o Conflito Inicial, Desenvolvimento, Clímax, Resolução e Conclusão, além das emoções e tópicos de 
    conversa associados. Você deve estruturar o roteiro de maneira clara, sem gerar falas, mas indicando o que 
    deve ser discutido ou expresso em cada momento do diálogo. Destaque as emoções e intenções que os personagens 
    devem transmitir em cada parte da narrativa, garantindo que o roteiro siga uma ordem lógica e emocionalmente 
    envolvente.

    <texto_base>
    {texto_base}
    </texto_base>    
   
  expected_output: >
    Você deverá entregar um roteiro estruturado que siga a sequência de Conflito Inicial, Desenvolvimento, Clímax, 
    Resolução e Conclusão. O roteiro deve indicar claramente os tópicos de conversa, as ações dos personagens e 
    as emoções ou intenções que devem ser expressas em momentos-chave. O resultado final deve ser um guia coeso e 
    fluido, que permita a um escritor ou diretor desenvolver diálogos envolventes e significativos com base nesse 
    roteiro.

tarefa_revisao_roteiro:
  description: >
    Sua tarefa é revisar o roteiro criado pelo Agente Roteirista, garantindo que ele seja coeso, consistente e fiel 
    ao contexto narrativo estabelecido pelo Agente Analista de Texto. Você deve verificar se o roteiro segue 
    corretamente a estrutura de Conflito Inicial, Desenvolvimento, Clímax, Resolução e Conclusão, analisando 
    também se as emoções e tópicos de conversa estão bem representados e se há transições fluidas entre as partes. 
    Em caso de inconsistências, sugerir ajustes que alinhem o roteiro com o contexto emocional e narrativo original.
   
    <texto_base>
    {texto_base}
    </texto_base>   
   
  expected_output: >
    Você deverá entregar um roteiro revisado, assegurando que todas as partes estejam bem conectadas e que o 
    contexto original, as emoções e os tópicos de conversa estejam preservados e consistentes. Caso encontre 
    inconsistências ou desvios, você deverá sugerir melhorias que garantam que o roteiro esteja coeso e envolvente, 
    fluindo de maneira lógica e alinhada com a narrativa estabelecida.